### ISSUE TITLE
curl command generation not consistent with http/https

### ISSUE THREAD

**Issue by JensWendt** [sukunis/OMERO.openlink#4]
The curl command generated via the `Create_OpenLink.py` script follows the specified `URL = "https://%s%s"` when it is displayed via the line `print(cmd)` in the `Activities` tab under the "i" button for additional infos.

But when I go into the OpenLink tab in the right pane the download command there is generated with `http`.
I assume this comes from `omero-openlink/omero_openlink/templates/omero_openlink/index.html` line 14 `value='{{s.cmd}}'`.
Where are those slots and the `slot.cmd` defined or how could I change the command generation for the right pane from `http` to `https`?

**Comment by sukunis** [comment]
solved with 140265153e8a3d3b4c211401e17bbbcf56d2dba7
